# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf83ddfaff1193810f40f3a6ddca6e4da87940457d819c6c12b34372f0734d71768bf6ea77a7fd66d22a5be8df3f331ce1c06d8f2b5d7136004acccc7ae5ced

test:
  secret_key_base: 580a8dbd986e96d5e64041d2d4832427129280017e09fb11c146ca39d3cde050f08f00f1ebe9863ef237c4eed5fcb398f1d54708c80968482acaf77505da0b98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
